#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Deterministically embed the explicitly selected original Apache-2.0 weights."""
import hashlib
from pathlib import Path
import sys

SHA = '76ef7a8c8376a1a921e2f055419d27b4eaeca425ac2b430dd3f14a89eae84be0'
data = Path(sys.argv[1]).read_bytes()
assert len(data) == 1880 and data[:8] == b'DCLN0001'
assert hashlib.sha256(data).hexdigest() == SHA
lines = ['// SPDX-License-Identifier: Apache-2.0',
         '// Original synthetic-trained balanced-edge WIDE_CONTEXT model; DCLN0001.',
         '// SHA256: ' + SHA,
         '// Generated by tests/depth_runtime/embed_model.py; do not hand-edit.',
         '#ifndef SCANNER_DEPTH_MODEL_DATA_H', '#define SCANNER_DEPTH_MODEL_DATA_H',
         '#include <cstdint>', 'namespace oc { namespace depth_test {',
         'static const uint8_t kModelData[] = {']
lines += ['    ' + ', '.join('0x%02x' % b for b in data[i:i+16]) + ','
          for i in range(0, len(data), 16)]
lines += ['};', '} }', '#endif', '']
Path(sys.argv[2]).write_text('\n'.join(lines))
